services:
  postgres:
    image: postgres:16-alpine
    container_name: nullpointertalk-postgres
    environment:
      POSTGRES_DB: nullpointertalk
      POSTGRES_USER: nullpointertalk
      POSTGRES_PASSWORD: nullpointertalk
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: nullpointertalk-mongo
    environment:
      MONGO_INITDB_DATABASE: nullpointertalk
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
