services:
  
  coturn:
    image: coturn/coturn:latest
    container_name: nullpointertalk-coturn
    network_mode: host
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    command: ["-c", "/etc/coturn/turnserver.conf"]

volumes:
  postgres-data:
  mongo-data:
