export const ICON_NAMES = [
  'mic',
  'mic-off',
  'headphones',
  'headphones-off',
  'camera',
  'camera-off',
  'screen-share',
  'screen-share-off',
  'music',
  'chat',
  'phone-off',
  'gear',
  'close',
  'volume',
  'signal',
  'arrow-down',
  'menu',
  'send',
  'edit',
  'plus',
  'trash',
] as const

export type IconName = (typeof ICON_NAMES)[number]
