export const ROOM_ICON_CATALOG = [
  { glyph: '💬', label: 'Conversa' },
  { glyph: '🎮', label: 'Jogos' },
  { glyph: '📚', label: 'Estudos' },
  { glyph: '🎵', label: 'Música' },
  { glyph: '🎬', label: 'Filmes e séries' },
  { glyph: '🎨', label: 'Arte' },
  { glyph: '💻', label: 'Programação' },
  { glyph: '⚽', label: 'Esportes' },
  { glyph: '🍕', label: 'Comida' },
  { glyph: '☕', label: 'Café' },
  { glyph: '🌙', label: 'Vida noturna' },
  { glyph: '🔥', label: 'Em alta' },
  { glyph: '🚀', label: 'Projetos' },
  { glyph: '🧠', label: 'Ideias' },
  { glyph: '🎲', label: 'Jogos de mesa' },
  { glyph: '📷', label: 'Fotografia' },
]
